diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
user.name=RatneshSingh21
user.mail=ratneshs1340@gmail.com
user.email=ratneshs1340@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
branch.main.vscode-merge-base=origin/main
branch.main.remote=origin
branch.main.merge=refs/heads/main
remote.origin.url=https://github.com/RatneshSingh21/Portfolio.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
